// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("ADDRESSDOCUMENTATION")]
    public partial class Addressdocumentation
    {
        public Addressdocumentation()
        {
            Parking = new HashSet<Parking>();
            Userprofile = new HashSet<Userprofile>();
        }

        [Key]
        public int DocumentationId { get; set; }
        [StringLength(50)]
        public string NickName { get; set; }
        [Required]
        [StringLength(10)]
        public string Type { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Required]
        [StringLength(10)]
        public string Latitude { get; set; }
        [Required]
        [StringLength(10)]
        public string Longitude { get; set; }
        [Required]
        [StringLength(100)]
        public string StreetName { get; set; }
        [Required]
        [StringLength(5)]
        public string AddressNumber { get; set; }
        [StringLength(50)]
        public string Complement { get; set; }
        [Required]
        [StringLength(50)]
        public string ContryName { get; set; }
        [Required]
        [StringLength(50)]
        public string CityName { get; set; }
        [Required]
        [StringLength(50)]
        public string NeighborhoodName { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [InverseProperty("AddressDocument")]
        public virtual ICollection<Parking> Parking { get; set; }
        [InverseProperty("AddressDocumentation")]
        public virtual ICollection<Userprofile> Userprofile { get; set; }
    }
}