// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("CARDOCUMENTATION")]
    public partial class Cardocumentation
    {
        [Key]
        public int CarDocumentationId { get; set; }
        [StringLength(50)]
        public string NickName { get; set; }
        [Required]
        [StringLength(10)]
        public string Type { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidTime { get; set; }
        [Required]
        [StringLength(255)]
        public string Information { get; set; }
        [StringLength(255)]
        public string StorageId { get; set; }
        public int UserId { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Userprofile.Cardocumentation))]
        public virtual Userprofile User { get; set; }
    }
}