// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("PARKINGSCHEDULE")]
    public partial class Parkingschedule
    {
        public Parkingschedule()
        {
            Rentparking = new HashSet<Rentparking>();
        }

        [Key]
        public int ParkingScheduleId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Day { get; set; }
        [StringLength(10)]
        public string Repetition { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidTime { get; set; }
        public int ParkingId { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(ParkingId))]
        [InverseProperty("Parkingschedule")]
        public virtual Parking Parking { get; set; }
        [InverseProperty("ParkingSchedule")]
        public virtual ICollection<Rentparking> Rentparking { get; set; }
    }
}