// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("PARKING")]
    public partial class Parking
    {
        public Parking()
        {
            Parkingschedule = new HashSet<Parkingschedule>();
        }

        [Key]
        public int ParkingId { get; set; }
        [StringLength(50)]
        public string NickName { get; set; }
        [Required]
        [StringLength(255)]
        public string Description { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal AmountMoney { get; set; }
        public int WalletId { get; set; }
        public int AddressDocumentId { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(AddressDocumentId))]
        [InverseProperty(nameof(Addressdocumentation.Parking))]
        public virtual Addressdocumentation AddressDocument { get; set; }
        [ForeignKey(nameof(WalletId))]
        [InverseProperty(nameof(Userwallet.Parking))]
        public virtual Userwallet Wallet { get; set; }
        [InverseProperty("Parking")]
        public virtual ICollection<Parkingschedule> Parkingschedule { get; set; }
    }
}