// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("RENTPARKING")]
    public partial class Rentparking
    {
        public Rentparking()
        {
            Parkingtransaction = new HashSet<Parkingtransaction>();
        }

        [Key]
        public int RentParkingId { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        public int ParkingScheduleId { get; set; }
        public int UserId { get; set; }
        public byte PercentageTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Day { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndTime { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal AmountMoney { get; set; }
        public int? UserVoucherId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(ParkingScheduleId))]
        [InverseProperty(nameof(Parkingschedule.Rentparking))]
        public virtual Parkingschedule ParkingSchedule { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Userprofile.Rentparking))]
        public virtual Userprofile User { get; set; }
        [ForeignKey(nameof(UserVoucherId))]
        [InverseProperty(nameof(Uservoucher.Rentparking))]
        public virtual Uservoucher UserVoucher { get; set; }
        [InverseProperty("RentParking")]
        public virtual ICollection<Parkingtransaction> Parkingtransaction { get; set; }
    }
}