// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("USERCREDITCARD")]
    public partial class Usercreditcard
    {
        public Usercreditcard()
        {
            Parkingtransaction = new HashSet<Parkingtransaction>();
        }

        [Key]
        public int UserCreditCardId { get; set; }
        [StringLength(50)]
        public string NickName { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime ValidTime { get; set; }
        [Required]
        [StringLength(255)]
        public string Information { get; set; }
        public int UserId { get; set; }
        public int CreditCardId { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(CreditCardId))]
        [InverseProperty(nameof(Creditcard.Usercreditcard))]
        public virtual Creditcard CreditCard { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Userprofile.Usercreditcard))]
        public virtual Userprofile User { get; set; }
        [InverseProperty("UserCreditCard")]
        public virtual ICollection<Parkingtransaction> Parkingtransaction { get; set; }
    }
}