// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("USERWALLET")]
    public partial class Userwallet
    {
        public Userwallet()
        {
            Parking = new HashSet<Parking>();
            Parkingtransaction = new HashSet<Parkingtransaction>();
        }

        [Key]
        public int UserWalletId { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal AmountMoney { get; set; }
        [Required]
        [StringLength(10)]
        public string CurrencyType { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [InverseProperty("UserWallet")]
        public virtual Userprofile Userprofile { get; set; }
        [InverseProperty("Wallet")]
        public virtual ICollection<Parking> Parking { get; set; }
        [InverseProperty("UserWallet")]
        public virtual ICollection<Parkingtransaction> Parkingtransaction { get; set; }
    }
}