// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("USERVOUCHER")]
    public partial class Uservoucher
    {
        public Uservoucher()
        {
            Rentparking = new HashSet<Rentparking>();
        }

        [Key]
        public int UserVoucherId { get; set; }
        [Required]
        [StringLength(10)]
        public string Status { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal? AmountMoney { get; set; }
        public int UserId { get; set; }
        public int VoucherId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty(nameof(Userprofile.Uservoucher))]
        public virtual Userprofile User { get; set; }
        [ForeignKey(nameof(VoucherId))]
        [InverseProperty("Uservoucher")]
        public virtual Voucher Voucher { get; set; }
        [InverseProperty("UserVoucher")]
        public virtual ICollection<Rentparking> Rentparking { get; set; }
    }
}