// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("USERPROFILE")]
    public partial class Userprofile
    {
        public Userprofile()
        {
            Rentparking = new HashSet<Rentparking>();
            Usercreditcard = new HashSet<Usercreditcard>();
            Uservoucher = new HashSet<Uservoucher>();
        }

        [Key]
        public int UserId { get; set; }
        [StringLength(50)]
        public string FirstName { get; set; }
        [StringLength(50)]
        public string LastName { get; set; }
        [StringLength(100)]
        public string Email { get; set; }
        [Required]
        [StringLength(20)]
        public string PhoneNumber { get; set; }
        [Required]
        [StringLength(10)]
        public string PhoneRegion { get; set; }
        [Required]
        [StringLength(10)]
        public string Language { get; set; }
        public byte MultiFactor { get; set; }
        public byte LastFailedLogin { get; set; }
        [StringLength(255)]
        public string FingerPrint { get; set; }
        public int? IdentificationId { get; set; }
        public int? DriverDocumentationId { get; set; }
        public int? AddressDocumentationId { get; set; }
        public int UserWalletId { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [ForeignKey(nameof(AddressDocumentationId))]
        [InverseProperty(nameof(Addressdocumentation.Userprofile))]
        public virtual Addressdocumentation AddressDocumentation { get; set; }
        [ForeignKey(nameof(DriverDocumentationId))]
        [InverseProperty(nameof(Driverdocumentation.Userprofile))]
        public virtual Driverdocumentation DriverDocumentation { get; set; }
        [ForeignKey(nameof(IdentificationId))]
        [InverseProperty("Userprofile")]
        public virtual Identification Identification { get; set; }
        [ForeignKey(nameof(UserWalletId))]
        [InverseProperty(nameof(Userwallet.Userprofile))]
        public virtual Userwallet UserWallet { get; set; }
        [InverseProperty("User")]
        public virtual Cardocumentation Cardocumentation { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Rentparking> Rentparking { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Usercreditcard> Usercreditcard { get; set; }
        [InverseProperty("User")]
        public virtual ICollection<Uservoucher> Uservoucher { get; set; }
    }
}