// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace KrakenStartup.test
{
    [Table("VOUCHER")]
    public partial class Voucher
    {
        public Voucher()
        {
            Uservoucher = new HashSet<Uservoucher>();
        }

        [Key]
        public int VoucherId { get; set; }
        [Column(TypeName = "decimal(5, 2)")]
        public decimal? AmountMoney { get; set; }
        public int? PercentageValue { get; set; }
        public int? MinimumPurchaseValue { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ValidTime { get; set; }
        public byte SingleUse { get; set; }
        public byte Enable { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreateTime { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? UpdateTime { get; set; }

        [InverseProperty("Voucher")]
        public virtual ICollection<Uservoucher> Uservoucher { get; set; }
    }
}